# Generated by Django 3.1.3 on 2021-01-05 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_start', models.TimeField()),
                ('slice_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StandardWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('slice_count', models.IntegerField(default=3)),
                ('slices', models.ManyToManyField(to='barber.TimeSlices')),
            ],
        ),
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slice_count', models.IntegerField(default=3)),
                ('slices', models.ManyToManyField(to='barber.TimeSlices')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 1, 5))),
                ('reason', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barber.credentials')),
                ('time_slice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barber.timeslices')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barber.treatments')),
            ],
        ),
    ]
