# Generated by Django 3.1.3 on 2021-01-12 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardweek',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 12)),
        ),
    ]
