# Generated by Django 3.1.3 on 2020-12-02 11:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('duration', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_path', models.CharField(max_length=400)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now_add=True)),
                ('barber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barbers')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Openinghours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('monday_end', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('tuesday_start', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('tuesday_end', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('wednesday_start', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('wednesday_end', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('thursday_start', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('thursday_end', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('friday_start', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('friday_end', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('saturday_start', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('saturday_end', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('sunday_start', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('sunday_end', models.TimeField(default=datetime.time(12, 35, 12, 679875))),
                ('last_edit', models.DateTimeField(auto_now_add=True)),
                ('barber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barbers')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now_add=True)),
                ('barber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barbers')),
            ],
        ),
        migrations.CreateModel(
            name='Worktimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('monday_end', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('tuesday_start', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('tuesday_end', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('wednesday_start', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('wednesday_end', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('thursday_start', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('thursday_end', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('friday_start', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('friday_end', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('saturday_start', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('saturday_end', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('sunday_start', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('sunday_end', models.TimeField(default=datetime.time(12, 35, 12, 680869))),
                ('last_edit', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.employees')),
            ],
        ),
        migrations.DeleteModel(
            name='Presets',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='treatment_array',
            new_name='treatment',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='booked_time_end',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='booked_time_start',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='date_booked',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='appointments',
            name='date_booked_end',
            field=models.TimeField(default=datetime.time(12, 35, 12, 678868)),
        ),
        migrations.AddField(
            model_name='appointments',
            name='date_booked_start',
            field=models.TimeField(default=datetime.time(12, 35, 12, 678868)),
        ),
        migrations.DeleteModel(
            name='QuestionConnections',
        ),
        migrations.DeleteModel(
            name='TreatmentQuestions',
        ),
        migrations.AddField(
            model_name='credentials',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.appointments'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.questions'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.employees'),
        ),
    ]
