# Generated by Django 3.1.3 on 2020-12-09 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_auto_20201209_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='duration',
            field=models.TimeField(default=datetime.time(23, 38, 50, 193951)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 38, 50, 193951)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 38, 50, 193951)),
        ),
        migrations.RemoveField(
            model_name='employees',
            name='work_time',
        ),
        migrations.AddField(
            model_name='employees',
            name='work_time',
            field=models.ManyToManyField(to='barber.Worktimes'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_close',
            field=models.TimeField(default=datetime.time(23, 38, 50, 193951)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_open',
            field=models.TimeField(default=datetime.time(23, 38, 50, 193951)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='end',
            field=models.TimeField(default=datetime.time(23, 38, 50, 193951)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='start',
            field=models.TimeField(default=datetime.time(23, 38, 50, 193951)),
        ),
    ]
