# Generated by Django 3.1.3 on 2021-03-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_auto_20210301_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardweek',
            name='slices',
            field=models.ManyToManyField(null=True, to='barber.TimeSlices'),
        ),
    ]
