# Generated by Django 3.1.3 on 2020-12-03 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_auto_20201202_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='barber_id',
            new_name='barber',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='openinghours',
            old_name='barber_id',
            new_name='barber',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='barber_id',
            new_name='barber',
        ),
        migrations.RenameField(
            model_name='worktimes',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='answers',
            name='duration',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='friday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='friday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='monday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='monday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 677956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='friday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='friday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='monday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='monday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='saturday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='saturday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='sunday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='sunday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(8, 48, 57, 678956)),
        ),
    ]
