# Generated by Django 3.1.3 on 2020-12-17 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_auto_20201216_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Timelices',
            new_name='Timeslices',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='credentials',
        ),
        migrations.AddField(
            model_name='appointments',
            name='credentials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='barber.credentials'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 10, 15, 41, 678347)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 10, 15, 41, 678347)),
        ),
        migrations.AlterField(
            model_name='daily',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
