# Generated by Django 3.1.3 on 2020-12-07 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_auto_20201203_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='wednesday_start',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='friday_end',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='friday_start',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='monday_end',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='monday_start',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='saturday_end',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='saturday_start',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='sunday_end',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='sunday_start',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='thursday_end',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='thursday_start',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='tuesday_end',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='tuesday_start',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='wednesday_end',
        ),
        migrations.RemoveField(
            model_name='worktimes',
            name='wednesday_start',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='day',
            field=models.CharField(default='<day>', max_length=10),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='time_close',
            field=models.TimeField(default=datetime.time(13, 5, 36, 542998)),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='time_open',
            field=models.TimeField(default=datetime.time(13, 5, 36, 542998)),
        ),
        migrations.AddField(
            model_name='worktimes',
            name='day',
            field=models.CharField(default='<day>', max_length=10),
        ),
        migrations.AddField(
            model_name='worktimes',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worktimes',
            name='time_close',
            field=models.TimeField(default=datetime.time(13, 5, 36, 544009)),
        ),
        migrations.AddField(
            model_name='worktimes',
            name='time_open',
            field=models.TimeField(default=datetime.time(13, 5, 36, 544009)),
        ),
        migrations.AlterField(
            model_name='answers',
            name='duration',
            field=models.TimeField(default=datetime.time(13, 5, 36, 544009)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 5, 36, 541997)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 5, 36, 541997)),
        ),
    ]
