# Generated by Django 3.1.3 on 2020-12-18 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_auto_20201218_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 10, 14, 57, 905865)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 10, 14, 57, 905865)),
        ),
    ]
