# Generated by Django 3.1.3 on 2020-12-07 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_auto_20201207_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='duration',
            field=models.TimeField(default=datetime.time(13, 13, 41, 982959)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='customer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 13, 41, 980959)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 13, 41, 980959)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_close',
            field=models.TimeField(default=datetime.time(13, 13, 41, 981959)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_open',
            field=models.TimeField(default=datetime.time(13, 13, 41, 981959)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='time_close',
            field=models.TimeField(default=datetime.time(13, 13, 41, 982959)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='time_open',
            field=models.TimeField(default=datetime.time(13, 13, 41, 982959)),
        ),
    ]
