# Generated by Django 3.1.3 on 2020-12-17 00:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_auto_20201217_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='credentials',
        ),
        migrations.AddField(
            model_name='appointments',
            name='credentials',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='barber.credentials'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 12, 17, 1, 58, 31, 988138)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(
                2020, 12, 17, 1, 58, 31, 988138)),
        ),
    ]
