# Generated by Django 3.1.3 on 2020-12-07 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_auto_20201207_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.AlterField(
            model_name='answers',
            name='duration',
            field=models.TimeField(default=datetime.time(13, 15, 24, 287002)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 15, 24, 285036)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 15, 24, 285036)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_close',
            field=models.TimeField(default=datetime.time(13, 15, 24, 286041)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_open',
            field=models.TimeField(default=datetime.time(13, 15, 24, 286041)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='time_close',
            field=models.TimeField(default=datetime.time(13, 15, 24, 287002)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='time_open',
            field=models.TimeField(default=datetime.time(13, 15, 24, 287002)),
        ),
    ]
