# Generated by Django 3.1.3 on 2021-01-04 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_auto_20201218_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=10)),
                ('slice_count', models.IntegerField(default=3)),
            ],
        ),
        migrations.RenameModel(
            old_name='Day',
            new_name='Changes',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 10, 0, 30, 242323)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 10, 0, 30, 242323)),
        ),
    ]
