# Generated by Django 3.1.3 on 2020-12-07 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0006_auto_20201207_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='employee',
        ),
        migrations.AddField(
            model_name='appointments',
            name='employee_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answers',
            name='duration',
            field=models.TimeField(default=datetime.time(13, 21, 10, 767748)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 21, 10, 766756)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 21, 10, 766756)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_close',
            field=models.TimeField(default=datetime.time(13, 21, 10, 766756)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_open',
            field=models.TimeField(default=datetime.time(13, 21, 10, 766756)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='time_close',
            field=models.TimeField(default=datetime.time(13, 21, 10, 767748)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='time_open',
            field=models.TimeField(default=datetime.time(13, 21, 10, 767748)),
        ),
    ]
