# Generated by Django 3.1.3 on 2021-01-04 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0006_auto_20210104_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardweek',
            name='date',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 10, 4, 3, 333270)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 10, 4, 3, 333270)),
        ),
    ]
