# Generated by Django 3.1.3 on 2020-12-08 09:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0007_auto_20201207_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='credentials',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='duration',
            field=models.TimeField(default=datetime.time(10, 22, 33, 775361)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 10, 22, 33, 774362)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 10, 22, 33, 773342)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_close',
            field=models.TimeField(default=datetime.time(10, 22, 33, 774362)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='time_open',
            field=models.TimeField(default=datetime.time(10, 22, 33, 774362)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='time_close',
            field=models.TimeField(default=datetime.time(10, 22, 33, 775361)),
        ),
        migrations.AlterField(
            model_name='worktimes',
            name='time_open',
            field=models.TimeField(default=datetime.time(10, 22, 33, 775361)),
        ),
    ]
