# Generated by Django 3.1.3 on 2021-01-04 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0007_auto_20210104_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 10, 39, 38, 905006)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 10, 39, 38, 905006)),
        ),
    ]
