# Generated by Django 3.1.3 on 2021-01-05 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0013_auto_20210104_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date_booked_end',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='date_requested',
        ),
        migrations.AddField(
            model_name='appointments',
            name='time_slice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='barber.timeslices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barber.credentials'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date_booked_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 9, 20, 13, 218435)),
        ),
        migrations.AlterField(
            model_name='changes',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
        migrations.AlterField(
            model_name='standardweek',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
    ]
