# Generated by Django 3.1.3 on 2021-01-05 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0014_auto_20210105_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date_booked_start',
        ),
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 1, 5)),
        ),
        migrations.AlterField(
            model_name='changes',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
        migrations.AlterField(
            model_name='standardweek',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
    ]
