# Generated by Django 3.1.3 on 2021-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0016_auto_20210105_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='changes',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
        migrations.AlterField(
            model_name='standardweek',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
    ]
