# Generated by Django 3.1.3 on 2021-01-18 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0018_auto_20210105_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 18)),
        ),
        migrations.AlterField(
            model_name='changes',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
        migrations.AlterField(
            model_name='standardweek',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
    ]
