# Generated by Django 3.1.3 on 2021-01-19 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0020_auto_20210119_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
        migrations.AlterField(
            model_name='standardweek',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
        migrations.CreateModel(
            name='WeekDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2021, 1, 19))),
                ('slices', models.ManyToManyField(to='barber.TimeSlices')),
            ],
        ),
    ]
