# Generated by Django 3.1.3 on 2021-02-25 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0021_auto_20210124_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 25)),
        ),
        migrations.AlterField(
            model_name='changes',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
        migrations.AlterField(
            model_name='standardweek',
            name='slices',
            field=models.ManyToManyField(to='barber.TimeSlices'),
        ),
    ]
